FROM node:16.10.0-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN rm -rf node_modules
RUN npm install
COPY . .
RUN npm run build
RUN [ -d dist/assets ] || mkdir -p dist/assets
EXPOSE 5040
CMD ["npm","start","PROD"]